### ISSUE TITLE
Tilgjengeliggjør biblioteket som en skyfunksjon

### ISSUE THREAD

**Issue by matsjs** [Informasjonsforvaltning/jsonschematordf#5]

**Comment by KjerstiSteien** [comment]
@KurtStian relevant?

**Comment by NilsOveTen** [comment]
> @NilsOveTen relevant?

Kanskje, hvis vi har lyst til å ha det kjørende som en skyfunksjon. Men jeg ser ikke helt hvorfor vi skulle hatt lyst til å prioritere det. Så lander vel på "Nei" som svar her, uansett om vi har tenkt å videreutvikle jsonschematordf eller ikke
